#!/usr/bin/env python
import sys
import yaml
import importlib

class StepData (object):
    name = ""
    module = ""
    file = ""
    result = ""

CONFIG_DIRECTORY = "./config/"
HEALTCH_PROCCESS_CONFIG = CONFIG_DIRECTORY+"Healthcheck.yml"

config_file_load = open(HEALTCH_PROCCESS_CONFIG,'r')
config = yaml.safe_load(config_file_load)

for _iterator in range(len(config["tasks"])):
    for _iterator2 in range(len(config["tasks"][_iterator]["steps"])):

        print "Esta es la informacion de la tarea " + config["tasks"][_iterator]["name"] + " el paso "  + config["tasks"][_iterator]["steps"][_iterator2]["name"] + " con el modulo " + config["tasks"][_iterator]["steps"][_iterator2]["module"]
        StepData.module_name=config["tasks"][_iterator]["steps"][_iterator2]["module"]
        StepData.config_name=config["tasks"][_iterator]["steps"][_iterator2]["name"]
        StepData.config_file=CONFIG_DIRECTORY+StepData.config_name+".yml"
        StepData.module = importlib.import_module('modules.'+StepData.module_name)
        StepData.result = StepData.module.main( StepData.config_file )
        print StepData.result[0]
        del StepData
