#!/usr/bin/env python
import sys
import yaml
import importlib

class StepData (object):
    def __init__(self,module_name, config_name):
        self.module_name = module_name
        self.config_name = config_name
    def result(self):
        config_file = CONFIG_DIRECTORY+self.config_name+".yml"
        module = importlib.import_module('modules.'+self.module_name)
        return module.main(config_file)

CONFIG_DIRECTORY = "./config/"
HEALTCH_PROCCESS_CONFIG = CONFIG_DIRECTORY+"Healthcheck.yml"

config_file_load = open(HEALTCH_PROCCESS_CONFIG,'r')
config = yaml.safe_load(config_file_load)

ResultMatrix = []

for _iterator in range(len(config["tasks"])):
    ResultMatrix.append([])
    for _iterator2 in range(len(config["tasks"][_iterator]["steps"])):

        ResultMatrix[_iterator].append(StepData(config["tasks"][_iterator]["steps"][_iterator2]["module"],config["tasks"][_iterator]["steps"][_iterator2]["name"]))
        print ResultMatrix[_iterator][_iterator2].result()[0]
